### ISSUE TITLE
知乎验证码方式改了

### ISSUE THREAD

**Issue by zhangweilun** [MatrixSeven/ZhihuSpider#1]
貌似现在很难登录了

**Comment by MatrixSeven** [comment]
的确是，但是这种方式也可以登录，两种验证码随机出现，具体出现情况没有看。
另外还有一个大招，那就是直接上cookie~

**Comment by MatrixSeven** [comment]
@zhangweilun  的确是，但是两种验证码都可以登录，具体出现规律没有看，另外还有一个大招，那就是直接甩cookie。。作为请求数据，其实登录仅仅是为了提供上下文的访问信息    逃~，
